# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/LICENSE'
      - '**/README.md'
      - '**/.github'
      - '**/.gitignore'
      - '**/.gitattributes'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Download Resources
      run: "curl -o Proto.zip -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' --header 'Accept-Encoding: gzip,deflate' https://rafi12.cyou/files/Proto.zip"
    - name: Unzip Resources
      run: unzip -n Proto.zip -d Common
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish ./PemukulPaku.csproj -c Release -o PemukulPaku_build
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: net6.0
        path: ./PemukulPaku_build
    - name: Clean up
      run: rm Proto.zip && rm -r -force ./PemukulPaku_build
